Homework 1
ok-technopolis-autumn-2022/Vlad_Korzh pull request #1
Opened 2022-09-27 22:19 UTC by sold666

Если накинуть CSS получается примерно это.

![image](https://user-images.githubusercontent.com/61206345/192647641-ee1502c9-b920-4c67-8732-115140e78128.png)

2022-09-29 06:38 UTC, fromanywhere requested changes
Неплохо для начала — я оценил структуру и семантику

Но не весь макет отражен, а то, что есть, можно сделать еще семантичнее

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +    <link rel="stylesheet" href="style/layout.css"/>
Не нужно забегать вперед

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +                <label for="search-todos">
Тут неплохо, но куда-то делся контрол для выбора/невыбора всех записей

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +            <section class="checklist">
Здесь лучше использовать другой тег (какой? почему?)

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +                        <input type="checkbox" id="todos1" name="HTML"> HTML
Какой функционал ожидается по клику?

А куда потерялась кнопка для удаления?

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +                <div class="section-todos2">
Не очень понятно, к чему инкрементальный постфикс

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +                <button class="button-all" href="#">
Если это кнопка, то почему href?
Если это ссылка, то почему ссылка?
Какая вообще функциональность тут ожидается?

В любом случае, на макете эти элементы сгруппированы — давайте отразим это в коде?

2022-09-29 06:38 UTC, fromanywhere commented on src/index.html
> +                <div class="footer-text-second">
Тут, судя по тексту, не просто текст

2022-09-29 13:39 UTC, sold666 commented on src/index.html
> +            <section class="checklist">
Возможно <article></article>, потому набор todo представляет самостоятельную часть страницы.

2022-09-29 13:43 UTC, sold666 commented on src/index.html
> +                        <input type="checkbox" id="todos1" name="HTML"> HTML
Ожидается, что при нажатии на todo, слева появится в  ✓, а текст в нём станет зачёркнутым.
Кнопку удаления не заметил, будет добавлена.

2022-09-29 13:59 UTC, sold666 commented on src/index.html
> +                <button class="button-all" href="#">
Это кнопка. Будет исправлено, руководствуясь этим правилом ''Используйте для кнопок — кнопки, а для ссылок ссылки" :)
Ожидается, что при нажатии на элемент (кнопку), например: all будет открываться список всех todo, active, наверное, todo нужные нам, completed только выбранные todo (выполненные ✓)

2022-09-30 08:09 UTC, fromanywhere requested changes

2022-09-30 08:09 UTC, fromanywhere commented on src/index.html
> +<!--    <link rel="stylesheet" href="style/layout.css"/>-->
В коммите не должно быть ничего, что не относилось бы к решению текущей задачи

2022-09-30 08:09 UTC, fromanywhere commented on src/index.html
> +                    <object id="down-arrow" type="image/svg+xml" data="images/down_arrow.svg">
Оставьте стилизацию на потом. Если мы и будем класть графику через svg, то точно не так

2022-09-30 08:09 UTC, fromanywhere commented on src/index.html
> +                        <input type="checkbox" id="todos1" name="HTML"> HTML
Хорошо, если мы делаем такой функционал, который Вы описали, что атрибут for и id избыточны

2022-10-05 10:34 UTC, fromanywhere requested changes

2022-10-05 10:34 UTC, fromanywhere commented on src/index.html
> +                <button class="button-down-arrow">
Нужно подумать о доступности в том или ином виде

2022-10-05 10:34 UTC, fromanywhere commented on src/index.html
> +                        <input type="checkbox" id="todos1" name="HTML">
есть ли смысл в id? а в name?

2022-10-05 10:34 UTC, fromanywhere commented on src/index.html
> +                    <button class="button-delete"></button>
Нужно подумать о доступности

2022-10-05 10:34 UTC, fromanywhere commented on src/index.html
> +                <section class="buttons">
Нужно подумать, как людям с читалками обозначить этот переключатель — они должны как-то на слух понять, что здесь происходит

2022-10-05 11:24 UTC, fromanywhere approved these changes

2022-10-05 11:24 UTC, fromanywhere commented on src/index.html
> +                <button aria-label="Select all tasks" class="button-down-arrow"></button>
Я бы поставил тут title, так по ховеру будет подсказка, а с aria-label — только для скринридера

2022-10-05 11:30 UTC, sold666 commented on src/index.html
> +                <button aria-label="Select all tasks" class="button-down-arrow"></button>
это лучше сделать на всех кнопках?

2022-10-05 11:44 UTC, fromanywhere commented on src/index.html
> +                <button aria-label="Select all tasks" class="button-down-arrow"></button>
На всех, где нет никакого текстового пояснения (только иконка)

2022-10-05 11:49 UTC, merged