Homework 2
ok-technopolis-autumn-2022/Vlad_Korzh pull request #2
Opened 2022-10-17 16:31 UTC by sold666

Начал работу над дизайном.
 
![image](https://user-images.githubusercontent.com/61206345/196232263-712e1831-5fe1-4e17-8ba8-dd27214f0264.png)

2022-10-18 07:42 UTC, fromanywhere requested changes
Старайтесь сразу максимизировать площадь всех интерактивных элементов, чтобы по ним было проще попасть. Если на десктопе, допустим, можно прицелиться мышью, то на телефоне попасть пальцем в мелкую кнопку будет сложно. Поэтому — тянем поле ввода по всей ширине и высоте строки; кнопки делаем по площади настолько большими, насколько возможно в рамках макета — иконку по центру, вокруг — просто прозрачная кликабельная область

2022-10-18 07:42 UTC, fromanywhere commented on src/style/layout.css
> +    width: 562px;
Подумайте сразу о том, что будет, если элементов в списке станет больше

2022-10-18 07:42 UTC, fromanywhere commented on src/style/layout.css
> +    width: 562px;
Старайтесь меньше использовать явно заданные размеры — это делает возможность быть Вашему продукту более гибким. В данном случае в ширине нет смысла, потому что она всё равно будет определяться родительским контейнером

2022-10-18 07:42 UTC, fromanywhere commented on src/style/layout.css
> +    box-shadow: inset 0 -1px 0 #E6E6E6;
Несмотря на то, что фигма предлагает делать линию через тень, это всё же border

2022-10-18 07:42 UTC, fromanywhere commented on src/style/layout.css
> +    float: right;
Это легально, но добавит Вам много проблем в дальнейнейшем написании стилей. Попробуйте через flex

2022-10-18 07:42 UTC, fromanywhere commented on src/style/layout.css
> +    line-height: 35px;
Как и все свойства шрифта, line-height может наследоваться от родителя. Нет смысла описывать его для каждого из потомков (да и вообще в этом месте лучше сделать вертикальное центрирование флексами)

2022-10-18 07:42 UTC, fromanywhere commented on src/style/layout.css
> +    letter-spacing: -0.35px;
Несмотря на макет, я не рекомендую использовать в верстке letter-spacing, потому что это ведет к сложностям в чтении этого текста на дисплеях с низкой разрешающей способностью (большое зерно пикселя), а также платформам с авторским сглаживанием шрифтов (linux)

2022-10-18 20:17 UTC, sold666 commented on src/style/layout.css
> +    width: 562px;
Решил эту проблему с помощью flex

2022-10-19 08:22 UTC, sold666 commented
Что добавил: 
-  flex box
- теперь при изменении размерности макет не съезжает
- добавление большого количества элементов в список учитывается
- box-shadow заменил на border
- letter-spacing были убраны
- интерактивные элементы увеличены в размере
- скрыл checkbox с помощью свойства overflow

2022-10-26 11:58 UTC, sold666 commented
Что добавил: 
- графика кнопок
- preconnects

Проблемы:
Всё так же не понимаю, как сделать поиск по всей ширине header..Всё остальное вроде работает.

![image](https://user-images.githubusercontent.com/61206345/198020376-7372dee0-fec1-4533-b98c-44e703cf21f0.png)

2022-10-26 12:00 UTC, sold666 commented
> Что добавил:
> 
> * графика кнопок
> * preconnects
> 
> Проблемы: Всё так же не понимаю, как сделать поиск по всей ширине header..Всё остальное вроде работает.
> 
> ![image](https://user-images.githubusercontent.com/61206345/198020376-7372dee0-fec1-4533-b98c-44e703cf21f0.png)

@fromanywhere пссс проверьте, пожалуйста ;(

2022-10-26 12:00 UTC, sold666 commented
> Что добавил:
> 
> * графика кнопок
> * preconnects
> 
> Проблемы: Всё так же не понимаю, как сделать поиск по всей ширине header..Всё остальное вроде работает.
> 
> ![image](https://user-images.githubusercontent.com/61206345/198020376-7372dee0-fec1-4533-b98c-44e703cf21f0.png)

2022-10-26 15:03 UTC, sold666 commented
Теперь это выглядит лучше
![image](https://user-images.githubusercontent.com/61206345/198062954-2c619114-b4aa-4d43-b831-ab86ae0b1127.png)

2022-10-26 15:34 UTC, fromanywhere requested changes
Прямоугольники можно попробовать повесить на footer

2022-10-26 15:34 UTC, fromanywhere commented on src/style/layout.css
> +    min-height: 66px;
если убрать обертку label (она не нужна) и сделать flex-grow:1, то всё заработает

2022-10-26 15:34 UTC, fromanywhere commented on src/style/layout.css
> +    display: flex;
Может быть вот так 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/1042969/198067365-9dadb90a-2cb5-4f5f-a6bb-a0e1e451965b.png">

2022-10-26 15:34 UTC, fromanywhere commented on src/style/layout.css
> +    background: url("../images/check_mark.png") no-repeat center;
нет никакого состояния на focus, непонятно, где находится пользователь при навигации с клавиатуры

2022-10-26 15:34 UTC, fromanywhere commented on src/style/layout.css
> +.button-delete:hover {
а на фокус?

2022-10-26 15:34 UTC, fromanywhere commented on src/style/layout.css
> +    background: url("../images/delete_button.png") no-repeat center;
графика мыльная

2022-10-26 15:34 UTC, fromanywhere commented on src/style/layout.css
> +    border: 1px solid #EBDFDF;
элементы прыгают по горизонтали при переключении между ними

2022-10-26 15:44 UTC, sold666 commented
> Прямоугольники можно попробовать повесить на footer

вы не поверите, я пробовал) сейчас попробую ещё раз

2022-10-26 21:39 UTC, sold666 commented
Для декораций сделал отдельные div, надеюсь, сильно бить не будете (с футером не получилось) :)

2022-10-27 15:54 UTC, fromanywhere commented
Стрелку разнесло 
<img width="125" alt="image" src="https://user-images.githubusercontent.com/1042969/198339028-ceea9380-c948-4100-b2b0-2ce4a5848c79.png">

2022-10-27 15:54 UTC, fromanywhere approved these changes

2022-10-27 21:16 UTC, merged