Homework 4
ok-technopolis-autumn-2022/Vlad_Korzh pull request #5
Opened 2022-11-20 11:41 UTC by sold666

Добавил JS

2022-11-21 10:01 UTC, fromanywhere requested changes
Сначала нужно исправить критичные замечания ниже, а затем подумать, можно ли разобрать этот код на более атомарные модули

2022-11-21 10:01 UTC, fromanywhere commented on src/scripts/index.js
> +                            p {
Но зачем писать стили в js?

2022-11-21 10:01 UTC, fromanywhere commented on src/scripts/index.js
> +var count = getNumberOfTodoFromStorage();
let?

2022-11-21 10:01 UTC, fromanywhere commented on src/scripts/index.js
> +    todosCheckList.innerHTML = newTask || notification;
xss

2022-11-21 10:01 UTC, fromanywhere commented on src/scripts/index.js
> +    let todo = todoInput.value.trim();
Здесь должен быть submit формы

2022-11-26 14:18 UTC, sold666 commented
Здравствуйте, Иван @fromanywhere. Я хочу задать вопрос по поводу замечания с XSS.. Я уже около недели пытаюсь разобраться, как это правильно пофиксить с localstorage. Я создал этот div с помощью createlement, как показывали на лекции, но я не понимаю как связать это с localstorage, чтобы он отображал вставляемый элемент...Спасите

2022-11-28 08:21 UTC, fromanywhere commented
Мне в почту упал вопрос относительно xss и localstorage, но я его тут почему-то не нашел.
Если это вызывает затруднения (хотя это совсем несвязанные вещи), я предлагаю в рамках этой работы следующую стратегию: не трогать локалсторадж (в нем прямо сейчас мало смысла), а проблему с xss обойти через построение элементов через dom api и .textContent вместо .innerHTML. Да, это громоздко и неудобно, но такая стратегия позволит Вам быстрее закрыть эту работу и перейти к более сложным вещам

2022-11-28 08:25 UTC, sold666 commented
> Мне в почту упал вопрос относительно xss и localstorage, но я его тут почему-то не нашел.
> Если это вызывает затруднения (хотя это совсем несвязанные вещи), я предлагаю в рамках этой работы следующую стратегию: не трогать локалсторадж (в нем прямо сейчас мало смысла), а проблему с xss обойти через построение элементов через dom api и .textContent вместо .innerHTML. Да, это громоздко и неудобно, но такая стратегия позволит Вам быстрее закрыть эту работу и перейти к более сложным вещам

Да, здравствуйте, Иван. Я разобрался, как решить проблему с local storage и dom api. Просто сейчас приходиться много переделывать из за построения элемента таким образом. Спасибо.

2023-06-08 16:54 UTC, merged